import{Router}from"express";import Product from"../models/Product.js";import Waitlist from"../models/Waitlist.js";import{protect,allow,permission}from"../middleware/auth.js";import{sendEmail}from"../services/notify.js";const r=Router();
r.get("/suggestions",async(req,res)=>{const q=(req.query.q||"").trim();if(!q)return res.json([]);res.json(await Product.find({$or:[{name:new RegExp(q,"i")},{brand:new RegExp(q,"i")},{category:new RegExp(q,"i")},{shape:new RegExp(q,"i")}]}).limit(8).select("name brand category shape"))});
r.get("/",async(req,res,next)=>{try{let q={};for(let k of["category","brand","shape","size","color","material","gender","collection"])if(req.query[k])q[k]=req.query[k];if(req.query.search)q.$or=[{name:new RegExp(req.query.search,"i")},{brand:new RegExp(req.query.search,"i")},{category:new RegExp(req.query.search,"i")},{shape:new RegExp(req.query.search,"i")}];if(req.query.minPrice||req.query.maxPrice)q.price={...(req.query.minPrice?{$gte:+req.query.minPrice}:{}),...(req.query.maxPrice?{$lte:+req.query.maxPrice}:{})};let sort=req.query.sort==="price"?"price":req.query.sort==="-price"?"-price":req.query.sort==="rating"?"-rating":"-createdAt",page=Math.max(1,+req.query.page||1),limit=Math.min(60,+req.query.limit||12);const total=await Product.countDocuments(q),items=await Product.find(q).sort(sort).skip((page-1)*limit).limit(limit);res.json({items,total,page,pages:Math.ceil(total/limit)})}catch(e){next(e)}});
r.post("/:id/notify",async(req,res,next)=>{try{if(!req.body.email)return res.status(400).json({message:"Email required"});await Waitlist.findOneAndUpdate({product:req.params.id,email:req.body.email},{},{upsert:true});res.json({message:"We'll notify you when this frame is back in stock."})}catch(e){next(e)}});
r.get("/:id",async(req,res,next)=>{try{const p=await Product.findById(req.params.id);if(!p)return res.status(404).json({message:"Product not found"});res.json(p)}catch(e){next(e)}});
r.post("/",protect,allow("admin","staff"),permission("catalog"),async(req,res,next)=>{try{res.status(201).json(await Product.create(req.body))}catch(e){next(e)}});
r.put("/:id",protect,allow("admin","staff"),permission("catalog"),async(req,res,next)=>{try{const before=await Product.findById(req.params.id),p=await Product.findByIdAndUpdate(req.params.id,req.body,{returnDocument:"after",runValidators:true});if(before&&before.stock<=0&&p?.stock>0){const rows=await Waitlist.find({product:p._id});for(const row of rows)await sendEmail(row.email,`${p.name} is back in stock`,`<p>${p.name} is available again at ORBIS.</p>`).catch(()=>{});await Waitlist.deleteMany({product:p._id})}res.json(p)}catch(e){next(e)}});
r.delete("/:id",protect,allow("admin"),async(req,res,next)=>{try{await Product.findByIdAndDelete(req.params.id);res.json({ok:true})}catch(e){next(e)}});
r.post("/bulk/import",protect,allow("admin"),async(req,res,next)=>{try{const rows=Array.isArray(req.body)?req.body:req.body.products;if(!Array.isArray(rows)||!rows.length)return res.status(400).json({message:"Send a JSON array of products"});const result=await Product.insertMany(rows,{ordered:false});res.status(201).json({imported:result.length})}catch(e){next(e)}});export default r;
